### ISSUE TITLE
Sectioned UITableView Without Indexes

### ISSUE THREAD

**Issue by syky27** [3lvis/DATASource#57]
Hi, according to README by doing this:

```swift
func sectionIndexTitlesForDataSource(dataSource: DATASource, tableView: UITableView) -> [String] {
    return [String]()
}
```

You can get rid of those indexes, that is correct and it works great but, in my app this causes memory leak.

Can you please check your app using this? It might me my mistake, but right now I am not sure at all.

Thanks

**Comment by 3lvis** [comment]
Hi @syky27,

I'm not sure how I would be able to fix that. Any ideas?

**Comment by syky27** [comment]
Well, same here basically it would be nice if the return value could be optional. So when you would not want any indexes you could return `nil` in `sectionIndexTitlesForDataSource`. But clearly, when I comment out that code, the memory leaks disappear.

I tried setting it up to optional return value but the indexes got rendered.

The weird thing I cannot wrap my head around is that `DATASource+UITableViewDataSource` line 29 `public func sectionIndexTitlesForTableView(tableView: UITableView) -> [String]? {` gets called twice for some reason...

**Comment by 3lvis** [comment]
@syky27 That delegate doesn't return an optional because I didn't found a way to do this if/else dance using an optional.

https://github.com/3lvis/DATASource/blob/master/Source/DATASource%2BUITableViewDataSource.swift#L29-L32

The method in line 29 is from `UITableViewDataSource`, just that DATASource overwrites all those delegates in order to provide some automatic functionality.

**Comment by 3lvis** [comment]
Closing this one until we find a good way to do it.

**Comment by syky27** [comment]
That's exactly why it should be opened, but whatever :)

**Comment by 3lvis** [comment]
@syky27 sorry, I'll rephrase:

Closing this one since doesn't seem to be a good way to fix this.
